executor: slurm
jobs: 300
default-resources:
    mem_mb_per_cpu: 2000
    runtime: 180
set-resources:
#    fit_ncfa:
#        slurm_partition: gpu_h100
#        slurm_extra: "'--gres=gpu:1'"
#    cross_validate_ncfa:
#        slurm_partition: gpu_h100
#        slurm_extra: "'--gres=gpu:1'"
