graph_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
seeds: [0, 1, 2, 3, 4]
sample_sizes: [1000, 5000]
lambda_values: [0.0, 0.2]
mu_values: [0.0, 0.2]

sparsities:
  7: 0.3
  8: 0.5
  9: 0.7
n_latent:
  7: 4
  8: 5
  9: 6
n_observed:
  7: 6
  8: 8
  9: 10